Change NuoDB loader to add new indexes and change sequence quantum.  Performance improvements to order_status.sql and payment.sql

diff --git a/bin/nuodb/dbt2-nuodb-load-db b/bin/nuodb/dbt2-nuodb-load-db
--- a/bin/nuodb/dbt2-nuodb-load-db
+++ b/bin/nuodb/dbt2-nuodb-load-db
@@ -138,7 +138,7 @@ create_tables() {
 #        primary key (d_w_id, d_id)
 #        )"
 
-    ORDER_SEQ="create sequence order_seq start with 3001"
+    ORDER_SEQ="create sequence order_seq quantum size 50000"
 
     DISTRICT="create table district (
         d_id int not null default '0',
@@ -184,6 +184,9 @@ create_tables() {
 
     CUSTOMER_PARTITION_KEY=c_w_id
 
+    CUSTOMER_LAST_NAME="create index customer_last_name on customer (
+        c_w_id, c_d_id, c_last)"
+
     HISTORY="create table history (
         h_c_id int,
         h_c_d_id int,
@@ -194,6 +197,8 @@ create_tables() {
         h_amount real,
         h_data varchar(24)
         )"
+
+    HISTORY_PARTITION_KEY=h_w_id
 
     NEW_ORDER="create table new_order (
         no_o_id int not null default '0',
@@ -215,6 +220,8 @@ create_tables() {
         o_all_local real,
         primary key (o_w_id, o_d_id, o_id)
         )"
+    ORDERS_C_ID="create index orders_c_id on orders (
+        o_w_id, o_d_id, o_c_id)"
 
     ORDERS_PARTITION_KEY=o_w_id
 
@@ -266,7 +273,7 @@ create_tables() {
 
     STOCK_PARTITION_KEY=s_w_id
 
-    TABLES="STOCK ITEM ORDER_LINE ORDERS NEW_ORDER HISTORY CUSTOMER ORDER_SEQ DISTRICT WAREHOUSE"
+    TABLES="STOCK ITEM ORDER_LINE ORDERS NEW_ORDER HISTORY CUSTOMER ORDER_SEQ DISTRICT WAREHOUSE CUSTOMER_LAST_NAME ORDERS_C_ID"
     for TABLE in $TABLES ;
     do
         echo "Creating table $TABLE"
@@ -282,6 +289,15 @@ create_tables() {
         command_exec "$NUODB_SQL ${DB_NAME}@${DB_HOST}:${DB_PORT} --user ${DB_USER} --password ${DB_PASSWORD} --schema ${DB_NAME} --file ${FILE}"
         rm -f $FILE
     done
+
+    FILE="$(mktemp 'XXXXXXXXXX.sql')" || { echo "Failed to create temp file"; exit 1; }
+    SEQCOUNT=0
+    while [ $SEQCOUNT -lt 3000 ]; do
+        echo "select next value for order_seq from dual;" >> $FILE
+        let SEQCOUNT++
+    done
+    command_exec "$NUODB_SQL ${DB_NAME}@${DB_HOST}:${DB_PORT} --user ${DB_USER} --password ${DB_PASSWORD} --schema ${DB_NAME} --file ${FILE}"
+    rm -f $FILE
 }
 
 TABLE_PARTITIONS=0
